
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 22-06-2021 10:35:28.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   core/src/main/java/hudson/views/ViewsTabBar.java , [85:9~92:23]
   core/src/main/java/hudson/views/MyViewsTabBar.java , [85:9~92:23]

*/


package hudson.views; // CAP AL
 // CAP AL
import java.util.ArrayList; // CAP AL
import java.util.Comparator; // CAP AL
import java.util.List; // CAP AL
import hudson.model.View; // CAP AL
 // CAP AL
public final class ExtractedSeparateClass60955 { // CAP AL
    private ExtractedSeparateClass60955() { // CAP AL
        throw new UnsupportedOperationException("This class cannot be instantiated"); // CAP AL
    } // CAP AL
     // CAP AL
    public static List<View> getResult59266(final List<? extends View> views) { // CAP AL
        List<View> result = new ArrayList<>(views); // CAP AL
        result.sort(new Comparator<View>() { // CAP AL
            @Override // CAP AL
            public int compare(View o1, View o2) { // CAP AL
                return o1.getDisplayName().compareTo(o2.getDisplayName()); // CAP AL
            } // CAP AL
        }); // CAP AL
        return result; // CAP AL
    } // CAP AL
} // CAP AL
