
/*

   Autogenerated by CAP duplicate fixer v1.1.0 at 22-06-2021 10:35:29.

   Locations of Issue Instances ( File, [StartLine:StartColumn ~ EndLine:EndColumn] ):

   test/src/test/java/hudson/slaves/AgentInboundUrlTest.java , [69:9~72:67]
   test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerTest.java , [314:9~318:67]
   test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerTest.java , [231:13~236:71]

*/


package hudson; // CAP AL
 // CAP AL
import jenkins.model.Jenkins; // CAP AL
import org.jvnet.hudson.test.JenkinsRule; // CAP AL
import org.jvnet.hudson.test.MockAuthorizationStrategy; // CAP AL
 // CAP AL
public final class ExtractedSeparateClass74998 { // CAP AL
    private ExtractedSeparateClass74998() { // CAP AL
        throw new UnsupportedOperationException("This class cannot be instantiated"); // CAP AL
    } // CAP AL
     // CAP AL
    public static void extractedMethod43598(final JenkinsRule r) { // CAP AL
        r.jenkins.setSecurityRealm(r.createDummySecurityRealm()); // CAP AL
         // CAP AL
        // let anonymous user have read access // CAP AL
        MockAuthorizationStrategy authorizationStrategy = new MockAuthorizationStrategy(); // CAP AL
        authorizationStrategy.grant(Jenkins.ADMINISTER).everywhere().toEveryone(); // CAP AL
        r.jenkins.setAuthorizationStrategy(authorizationStrategy); // CAP AL
    } // CAP AL
} // CAP AL
